### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by ryanmerolle** [itdependsnetworks/awesome-network-automation#33]
I think we need to look at organization a little and fix this up all up a little.  I need to think some more about it.  Initial thoughts:

- When adding content, I was not always sure of where to add material given some overlap of sections
- Definitions for each section might help keep content focused
- It may be hard keeping up with every podcast and article.  I think exceptional podcasts and articles should be highlighted, but maybe we can work with some of these websites to tag content and provide in a RSS feed

**Comment by itdependsnetworks** [comment]
Agreed on first two, on the third one it's only individual podcasts, and there is not currently a lot.

**Comment by itdependsnetworks** [comment]
I think we can close this, any update needed, a PR should be fine.
