### ISSUE TITLE
Programming should link other awesome list

### ISSUE THREAD

**Issue by koppor** [itdependsnetworks/awesome-network-automation#45]
Currently, the programming content (https://github.com/itdependsnetworks/awesome-network-automation#programming-topics) is just an itemized list and nothing awesome.

- JSON: https://github.com/burningtree/awesome-json
- YAML: https://github.com/dreftymac/awesome-yaml
- XML: Not yet existing

**Comment by itdependsnetworks** [comment]
thanks, and completed.
